spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:routinise;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  security:
    user:
      password: 1

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
